export const reportFixture = {
    id: 1,
    num_usp: '123456',
    dataAtualizacaoLattes: '2023-01-01',
    resultadoUltimoRelatorio: 'Aprovado' as 'Aprovado' | 'Aprovado com ressalvas' | 'Insatisfatório' | 'Não se aplica (é o meu primeiro relatório)',
    disciplinasAprovacoes: 5,
    disciplinasReprovacoes: 1,
    disciplinasReprovacoesDesdeInicio: 2,
    exameProficienciaIdiomas: 'Aprovado' as 'Aprovado' | 'Reprovado' | 'Não',
    exameQualificacao: 'Aprovado' as 'Aprovado' | 'Reprovado' | 'Não',
    prazoQualificacao: '2023-06-01',
    prazoDissertacao: '2024-01-01',
    artigosFaseEscrita: 1,
    artigosSubmetidos: 2,
    artigosAceitosPublicados: 3,
    atividadesAcademicas: 'Research',
    resumoAtividadesPesquisa: 'Summary',
    declaracaoAdicional: 'Additional declaration',
    dificuldadeApoio: 'Sim' as 'Sim' | 'Não',
    professorParecer: 'Aprovado' as 'Aprovado' | 'Aprovado com ressalvas' | 'Insatisfatório' | 'Sem parecer',
    professorComentario: 'Good progress',
    coordenadorParecer: 'Aprovado' as 'Aprovado' | 'Aprovado com ressalvas' | 'Insatisfatório' | 'Sem parecer',
    coordenadorComentario: 'Keep up the good work'
}